file_format: "1"
id: crumple
name: Crumple
type: shield
url: https://github.com/dillonbheadley/zmk-config-staggersaurus/
requires: [pro_micro]
features:
  - keys
siblings:
  - crumple_left
  - crumple_right
